sudo: required

services:
  - docker

language: go

go:
  - '1.5'

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build main.go
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO=isaachbn/docker-notify-api
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t -i $COMMIT .
  - docker tag $COMMIT $REPO:$TAG
  - docker push $REPO