front:
  build: .
  ports:
    - "8080:80"
    - "2222:22"
    - "9000:9000"
  links:
    - mongo:mongo
    - redis:redis
mongo:
  image: mongo
  ports:
    - "27018:27017"
redis:
  image: redis
  ports:
    - "6379:6379"